"""WaveView handoff: generate an ACE (Tcl) script that opens a run's FSDB
waveforms, displays selected signals, and saves a reusable .sx session.

Design (facts from "WaveView ACE Command Reference" and "WaveView User Guide",
both Y-2026.03-SP1; page numbers cite those documents):

- The .sx session format is UNDOCUMENTED (confirmed across the 956-page user
  guide) — this module therefore never writes .sx directly. It emits a Tcl ACE
  script using documented commands and lets WaveView itself produce the session
  via ``sx_save_session <file> -relpath`` (ACE ref p.212).
- First launch: ``wv -k -ace_gui <script>.tcl`` (ACE ref pp.20-21; ``-k`` skips
  the greeting window, user guide p.46). Reopen: ``wv -x <prefix>.sx``.
  Retarget the saved layout onto a NEW run's waveforms:
  ``wv -y <prefix>.sx <new>.fsdb`` (user guide p.50).
- Signals are brace-quoted Tcl literals; explicit signal paths are preferred
  over wildcards because huge FSDBs load scopes lazily (user guide,
  ``read_top_hier`` preference).

Whether a generated script actually opens in a licensed WaveView is a G2-class
check (one command on site); generation itself is fully offline-testable.
"""
from __future__ import annotations

import os
import re
from pathlib import Path
from typing import List, Optional

from primesim_bridge.parsers import collect_outputs

# .probe/.print statements in an HSPICE-format deck, e.g.
#   .probe tran v(out) i(vdd) x1.v(net5)
#   .PRINT AC vdb(out)
_PROBE_RE = re.compile(r"^\s*\.(?:probe|print)\b(.*)$", re.IGNORECASE)
_ANALYSIS_WORDS = {"tran", "ac", "dc", "noise", "sw"}
_SIGNAL_TOKEN_RE = re.compile(r"^[A-Za-z_][\w.\[\]]*(\([^()\s]+\))?$")

MAX_SIGNALS = 64


def parse_probe_signals(deck_text: str) -> List[str]:
    """Best-effort signal list from .probe/.print lines (order kept, deduped)."""
    seen: List[str] = []
    for line in deck_text.splitlines():
        m = _PROBE_RE.match(line)
        if not m:
            continue
        for tok in m.group(1).split():
            if tok.lower() in _ANALYSIS_WORDS or tok.startswith("$"):
                continue
            # drop output-variable assignments like out=v(x); keep the rhs
            if "=" in tok:
                tok = tok.split("=", 1)[1]
            if _SIGNAL_TOKEN_RE.match(tok) and tok not in seen:
                seen.append(tok)
    return seen


def _tcl_brace(literal: str) -> str:
    """Brace-quote a Tcl literal; refuse strings braces cannot carry."""
    if any(c in literal for c in "{}\n\r"):
        raise ValueError(f"cannot represent in a Tcl brace literal: {literal!r}")
    return "{" + literal + "}"


def emit_ace_script(
    fsdb_files: List[Path],
    signals: List[str],
    session_path: Optional[Path],
) -> str:
    """Render the ACE Tcl script text (pure function — snapshot-testable)."""
    lines = [
        "# Generated by primesim-bridge — WaveView ACE (Tcl) handoff script.",
        "# Launch:  wv -k -ace_gui <this file>   (then reopen: wv -x <session>.sx,",
        "#          retarget onto a new run: wv -y <session>.sx <new>.fsdb)",
    ]
    for f in fsdb_files:
        lines.append(f"sx_open_sim_file_read {_tcl_brace(str(f))}")
    if signals:
        lines.append("sx_signal_add_mode single")
        for s in signals[:MAX_SIGNALS]:
            lines.append(f"sx_display {_tcl_brace(s)} -auto_new_wv")
        if len(signals) > MAX_SIGNALS:
            lines.append(
                f"# {len(signals) - MAX_SIGNALS} more probed signals omitted"
                f" (cap {MAX_SIGNALS}) — add manually or raise the cap"
            )
    if session_path is not None:
        lines.append(f"sx_save_session {_tcl_brace(str(session_path))} -relpath")
    return "\n".join(lines) + "\n"


def find_fsdb_files(prefix: Path) -> List[Path]:
    return sorted(collect_outputs(prefix)["waveform"])


def write_waveview_script(
    prefix: Path,
    *,
    deck_text: str = "",
    signals: Optional[List[str]] = None,
    save_session: bool = True,
) -> dict:
    """Generate ``<prefix>_waves.tcl`` next to the run artifacts.

    Returns {"script", "session", "fsdb_files", "signals", "launch", "warnings"};
    "script" is None when no waveform files exist (nothing is written).
    """
    warnings: List[str] = []
    fsdb = [p for p in find_fsdb_files(prefix) if p.suffix == ".fsdb"]
    if not fsdb:
        return {
            "script": None,
            "session": None,
            "fsdb_files": [],
            "signals": [],
            "launch": [],
            "warnings": ["no .fsdb waveform files found for this prefix"],
        }
    sigs = list(signals) if signals else parse_probe_signals(deck_text)
    if not sigs:
        warnings.append(
            "no signals selected (none passed, none found in .probe/.print) — "
            "script opens the waveform files only"
        )
    session = prefix.with_suffix(".sx") if save_session else None
    script_path = prefix.parent / f"{prefix.name}_waves.tcl"
    script_path.write_text(emit_ace_script(fsdb, sigs, session))
    # Sites commonly launch WaveView through a wrapper (e.g. sx_sub) — honor it.
    wv = os.environ.get("PSB_WV_BIN", "wv")
    launch = [f"{wv} -k -ace_gui {script_path}"]
    if session is not None:
        launch.append(f"{wv} -x {session}")
        launch.append(f"{wv} -y {session} <new_run>.fsdb")
    return {
        "script": script_path,
        "session": session,
        "fsdb_files": fsdb,
        "signals": sigs,
        "launch": launch,
        "warnings": warnings,
    }
